# Site settings
title: AutoNotes
description: A generative knowledge base powered by Gemini AI.
url: "https://coltonchrane.dev"
baseurl: "/AutoNotes"
favicon_ico: "/favicon.ico"

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-relative-links
  - jemoji
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-sitemap

# Just the Docs settings
# This ensures the search works correctly on GitHub Pages
aux_links:
  "AutoNotes on GitHub": "https://github.com/coltonchrane/AutoNotes"
aux_links_new_tab: true
